language: ruby
rvm: 2.1.1
install: gem install kwalify
before_install: wget https://loot.github.io/masterlist.schema.yaml
script: kwalify -f masterlist.schema.yaml masterlist.yaml

notifications:
  irc:
    channels:
      - "chat.freenode.net#loot"
    use_notice: true
    skip_join: true
